### ISSUE TITLE
Cluster Def traceback while running wait_for_hosts.rb

### ISSUE THREAD

**Issue by cbaenziger** [bloomberg/chef-bach#1180] opened 2018-04-17 23:54 UTC
On current master I see the following while wait for hosts scrolls by:

```Searching for installed hosts, attempt 5/120
undefined method `[]' for nil:NilClass
/home/vagrant/chef-bcpc/lib/cluster-def-gem/lib/cluster_def.rb:135:in `fetch_cluster_def_http'
/home/vagrant/chef-bcpc/lib/cluster-def-gem/lib/cluster_def.rb:123:in `fetch_cluster_def'
/home/vagrant/chef-bcpc/wait_for_hosts.rb:137:in `listening_hosts'
/home/vagrant/chef-bcpc/wait_for_hosts.rb:155:in `block in <top (required)>'
/home/vagrant/chef-bcpc/wait_for_hosts.rb:150:in `each'
/home/vagrant/chef-bcpc/wait_for_hosts.rb:150:in `<top (required)>'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
/opt/chefdk/embedded/bin/bundle:22:in `load'
/opt/chefdk/embedded/bin/bundle:22:in `<main>'
	Booted hosts from apache log (4/4):
		10.0.100.11: stage-3
		10.0.100.12: stage-3
		10.0.100.13: stage-3
		10.0.100.14: stage-3

	Completed installations from apache log (4/4):
		bcpc-vm1, bcpc-vm2, bcpc-vm3, bcpc-vm4

	Installed hosts that are listening for SSH on port 22 (1/4):
		bcpc-vm3

	Hosts still missing (3/4):
		bcpc-vm1, bcpc-vm2, bcpc-vm4
```

**Comment by vt0r** [comment] 2018-04-17 23:56
Duplicate of #1157

**Closed by vt0r** 2018-04-17 23:56 UTC
Labels: Ruby
