### ISSUE TITLE
job history server file is not rotated and is filling up disk 

### ISSUE THREAD

**Issue by pu239ppy** [bloomberg/chef-bach#631] opened 2016-08-01 21:51 UTC
This needs to be fixed soon as we keep filling up /

**Comment by cbaenziger** [comment] 2016-08-01 21:59
For reference, example entries filling the log are:
````
16/07/216/07/26 12:02:32 INFO logaggregation.AggregatedLogDeletionService: Deleting aggregated logs in hdfs://CLUSTER/var/log/hadoop-yarn/apps/username/logs/application_1466181788431_5963
16/07/26 12:02:32 INFO logaggregation.AggregatedLogDeletionService: Deleting aggregated logs in hdfs://CLUSTER/var/log/hadoop-yarn/apps/username/logs/application_1466181788431_5966
16/07/26 12:02:32 INFO logaggregation.AggregatedLogDeletionService: Deleting aggregated logs in hdfs://CLUSTER/var/log/hadoop-yarn/apps/username/logs/application_1466181788431_59996 12:02:32 INFO logaggregation.AggregatedLogDeletionService: Deleting aggregated logs in hdfs://CLUSTER/var/log/hadoop-yarn/apps/username/logs/application_1466181788431_5963
16/07/26 12:02:32 INFO logaggregation.AggregatedLogDeletionService: Deleting aggregated logs in hdfs://CLUSTER/var/log/hadoop-yarn/apps/username/logs/application_1466181788431_5966
16/07/26 12:02:32 INFO logaggregation.AggregatedLogDeletionService: Deleting aggregated logs in hdfs://CLUSTER/var/log/hadoop-yarn/apps/username/logs/application_1466181788431_5999
````

**Comment by bijugs** [comment] 2016-08-02 15:15
Duplicate of #594?

**Closed** 2018-11-27 16:59 UTC
Labels: Chef, YARN
