### ISSUE TITLE
Master build is failing without http_proxy on Mac

### ISSUE THREAD

**Issue by amithkanand** [bloomberg/chef-bach#663] opened 2016-09-09 14:33 UTC
I am getting following error while building chef-bach master branch on a Mac and Ubuntu Desktop

```
+ USER=vagrant
+ ENVIRONMENT=Test-Laptop
+ load_binary_server_info Test-Laptop
+ environment=Test-Laptop
+ bootstrap_server_key='["override_attributes"]["bcpc"]["bootstrap"]["server"]'
+ binary_server_key='["override_attributes"]["bcpc"]["binary_server_url"]'
+ load_json_frag='import json; print json.load(file('\''environments/Test-Laptop.json'\''))'
++ python -c 'import json; print json.load(file('\''environments/Test-Laptop.json'\''))["override_attributes"]["bcpc"]["binary_server_url"]'
++ echo -n http://
++ python -c 'import json; print json.load(file('\''environments/Test-Laptop.json'\''))["override_attributes"]["bcpc"]["bootstrap"]["server"]+'\'':80'\'''
Traceback (most recent call last):
  File "<string>", line 1, in <module>
IOError: [Errno 2] No such file or directory: 'environments/Test-Laptop.json'
+ export binary_server_url=http://
+ binary_server_url=http://
++ ruby -e 'require '\''uri'\''; print URI('\''http://'\'').host'
/usr/lib/ruby/1.8/uri/common.rb:406:in `split': bad URI(absolute but no path): http:// (URI::InvalidURIError)
        from /usr/lib/ruby/1.8/uri/common.rb:485:in `parse'
        from /usr/lib/ruby/1.8/uri/common.rb:608:in `URI'
        from -e:1
+ export binary_server_host=
+ binary_server_host=
+ [[ -f .chef/knife.rb ]]
+ mkdir .chef
+ cat
++ pwd
++ pwd
++ pwd
+ mkdir -p ./vendor
+ /opt/chefdk/bin/berks vendor ./vendor/cookbooks
[2016-09-09T13:22:33+00:00] WARN: Ohai::Config[:log_level] is set. Ohai::Config[:log_level] is deprecated and will be removed in future releases of ohai. Use ohai.log_level in your configuration file to configure :log_level for ohai.
[2016-09-09T13:22:33+00:00] WARN: Ohai::Config[:disabled_plugins] is set. Ohai::Config[:disabled_plugins] is deprecated and will be removed in future releases of ohai. Use ohai.disabled_plugins in your configuration file to configure :disabled_plugins for ohai.
/opt/chefdk/embedded/lib/ruby/2.1.0/uri/common.rb:146:in `split': bad URI(absolute but no path): http:// (URI::InvalidURIError)
        from /opt/chefdk/embedded/lib/ruby/2.1.0/uri/common.rb:712:in `split'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-config-12.11.18/lib/chef-config/config.rb:873:in `export_proxy'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-config-12.11.18/lib/chef-config/config.rb:853:in `export_proxies'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.5.1/lib/ridley/chef/config.rb:15:in `initialize'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/lib/berkshelf.rb:90:in `new'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/lib/berkshelf.rb:90:in `chef_config'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/lib/berkshelf/config.rb:80:in `<class:Config>'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/lib/berkshelf/config.rb:4:in `<module:Berkshelf>'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/lib/berkshelf/config.rb:3:in `<top (required)>'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/lib/berkshelf/cookbook_generator.rb:3:in `require_relative'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/lib/berkshelf/cookbook_generator.rb:3:in `<class:CookbookGenerator>'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/lib/berkshelf/cookbook_generator.rb:2:in `<module:Berkshelf>'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/lib/berkshelf/cookbook_generator.rb:1:in `<top (required)>'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/lib/berkshelf.rb:197:in `require_relative'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/lib/berkshelf.rb:197:in `<top (required)>'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/lib/berkshelf/cli.rb:1:in `<top (required)>'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.3.5/bin/berks:3:in `<top (required)>'
        from /opt/chefdk/bin/berks:45:in `load'
        from /opt/chefdk/bin/berks:45:in `<main>'
Connection to 127.0.0.1 closed.
+ ./enroll_cobbler.sh
~/master/vbox ~/master
Registering bcpc-vm1 with 08:00:27:B9:D2:DA for 10.0.100.11
Base directory is : /home/amit/master/environments
sudo: cobbler: command not found
sudo: cobbler: command not found
Connection to 127.0.0.1 closed.
+ echo '############## VBOX CREATE INSTALL CLUSTER RETURNED 1 ##############'
############## VBOX CREATE INSTALL CLUSTER RETURNED 1 ##############
+ exit 1
```

**Comment by http-418** [comment] 2016-09-09 14:35
Amit, it looks like your `http_proxy` variable is set incorrectly.

I believe an empty, but exported, `http_proxy` is an error.

**Comment by http-418** [comment] 2016-09-09 15:02
It looks like the binary_server_url is empty, too.   That's particularly weird.

**Comment by amithkanand** [comment] 2016-09-09 15:28
when building clusters on external machines we never set http_proxy. Also, binary server URL is not set manually at all.

**Comment by cbaenziger** [comment] 2016-09-15 19:15
I was unable to reproduce this on my Linux machine at home.

**Comment by cbaenziger** [comment] 2016-09-15 19:27
Of course I mark this as could not reproduce right as @snukavarapu reproduces this, from his install log:
````
+ load_binary_server_info Test-Laptop
+ environment=Test-Laptop
+ bootstrap_server_key='["override_attributes"]["bcpc"]["bootstrap"]["server"]'
+ binary_server_key='["override_attributes"]["bcpc"]["binary_server_url"]'
+ load_json_frag='import json; print json.load(file('\''environments/Test-Laptop.json'\''))'
++ python -c 'import json; print json.load(file('\''environments/Test-Laptop.json'\''))["override_attributes"]["bcpc"]["binary_server_url"]'
++ echo -n http://
++ python -c 'import json; print json.load(file('\''environments/Test-Laptop.json'\''))["override_attributes"]["bcpc"]["bootstrap"]["server"]+'\'':80'\'''
Traceback (most recent call last):
  File "<string>", line 1, in <module>
IOError: [Errno 2] No such file or directory: 'environments/Test-Laptop.json'
+ export binary_server_url=http://
+ binary_server_url=http://
++ ruby -e 'require '\''uri'\''; print URI('\''http://'\'').host'
/usr/lib/ruby/1.8/uri/common.rb:406:in `split': bad URI(absolute but no path): http:// (URI::InvalidURIError)
        from /usr/lib/ruby/1.8/uri/common.rb:485:in `parse'
        from /usr/lib/ruby/1.8/uri/common.rb:608:in `URI'
        from -e:1
````

**Comment by snukavarapu** [comment] 2016-09-15 20:56
Attached is the complete log. 
[install.out.zip](https://github.com/bloomberg/chef-bach/files/475567/install.out.zip)

**Comment by cbaenziger** [comment] 2016-09-16 22:52
@snukavarapu Can you try deleting all your VM's but leaving the hotfix for Chef-BACH #665 in place and also modifying[line 82 of bootstrap_chef.sh](https://github.com/bloomberg/chef-bach/blob/9600c76c1288501e341cd6e82ee4b884d5fbf0c0/bootstrap_chef.sh#L82) by moving it to line 71 (before all the shell scripts get called)?

**Comment by snukavarapu** [comment] 2016-09-21 15:13
@cbaenziger, I have made changes to bootstrap_chef.sh and reran the ./tests/automated_install.sh. It is hitting the same error. Attached the log. 
[install.txt](https://github.com/bloomberg/chef-bach/files/485367/install.txt)

**Closed** 2016-09-22 23:32 UTC
Labels: bug, Chef
